import { storiesOf } from '@storybook/react';
import * as React from 'react';
import { Canceled as FilledCancel } from '../../../src/icons/Canceled';
import { ChevronDown as AdaptiveChevronDown } from '../../../src/icons/ChevronDown';
import { Complete as FilledComplete } from '../../../src/icons/Complete';
import { Error as FilledError } from '../../../src/icons/Error';
import { File as FilledFile } from '../../../src/icons/File';
import { Folder as FilledFolder } from '../../../src/icons/Folder';
import { Guide as AdaptiveGuide } from '../../../src/icons/Guide';
import { Heart as FilledHeart } from '../../../src/icons/Heart';
import { Info as FilledInfo } from '../../../src/icons/Info';
import {
  Activity,
  Airplay,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Anchor,
  Aperture,
  Archive,
  ArrowDown,
  ArrowDownCircle,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowLeft,
  ArrowLeftCircle,
  ArrowRight,
  ArrowRightCircle,
  ArrowUp,
  ArrowUpCircle,
  ArrowUpLeft,
  ArrowUpRight,
  AtSign,
  Award,
  BarChart,
  Battery,
  BatteryCharging,
  Bell,
  BellOff,
  Bluetooth,
  Bold,
  Book,
  Bookmark,
  BookOpen,
  Box,
  Briefcase,
  Calendar,
  Camera,
  CameraOff,
  Cast,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  ChevronUp,
  Chrome,
  Circle,
  Clipboard,
  Clock,
  Cloud,
  CloudDrizzle,
  CloudLightning,
  CloudOff,
  CloudRain,
  CloudSnow,
  Code,
  Codepen,
  Coffee,
  Command,
  Compass,
  Copy,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftDown,
  CornerLeftUp,
  CornerRightDown,
  CornerRightUp,
  CornerUpLeft,
  CornerUpRight,
  Cpu,
  CreditCard,
  Crop,
  Crosshair,
  Database,
  Delete,
  Disc,
  DollarSign,
  Download,
  DownloadCloud,
  Droplet,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  Facebook,
  FastForward,
  Feather,
  File,
  FileMinus,
  FilePlus,
  FileText,
  Film,
  Filter,
  Flag,
  Folder,
  FolderMinus,
  FolderPlus,
  Frown,
  Gift,
  GitBranch,
  GitCommit,
  GitHub,
  Gitlab,
  GitMerge,
  GitPullRequest,
  Globe,
  Grid,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  Image,
  Inbox,
  Info,
  Instagram,
  Italic,
  Key,
  Layers,
  Layout,
  LifeBuoy,
  Link,
  Link2,
  Linkedin,
  List,
  Loader,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPin,
  Maximize,
  Maximize2,
  Meh,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  MicOff,
  Minimize,
  Minimize2,
  Minus,
  MinusCircle,
  MinusSquare,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Move,
  Music,
  Navigation,
  Navigation2,
  Octagon,
  Package,
  Paperclip,
  Pause,
  PauseCircle,
  Percent,
  Phone,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  PieChart,
  Play,
  PlayCircle,
  Plus,
  PlusCircle,
  PlusSquare,
  Pocket,
  Power,
  Printer,
  Radio,
  RefreshCcw,
  RefreshCw,
  Repeat,
  Rewind,
  RotateCcw,
  RotateCw,
  Rss,
  Save,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Share2,
  Shield,
  ShieldOff,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sidebar,
  SkipBack,
  SkipForward,
  Slack,
  Slash,
  Sliders,
  Smartphone,
  Smile,
  Speaker,
  Square,
  Star,
  StopCircle,
  Sun,
  Sunrise,
  Sunset,
  Tablet,
  Tag,
  Target,
  Terminal,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  ToggleLeft,
  ToggleRight,
  Trash,
  Trello,
  TrendingDown,
  TrendingUp,
  Triangle,
  Truck,
  Tv,
  Twitter,
  Type,
  Umbrella,
  Underline,
  Unlock,
  Upload,
  UploadCloud,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  Users,
  UserX,
  Video,
  VideoOff,
  Voicemail,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Watch,
  Wifi,
  WifiOff,
  Wind,
  X,
  XCircle,
  XSquare,
  Youtube,
  Zap,
  ZapOff,
  ZoomIn,
  ZoomOut,
} from '../../../src/icons/lined';
import {
  AccessPolicy as LinedCustomAccessPolicy,
  ActivityFolder as LinedCustomActivityFolder,
  ActivityMonitor as LinedCustomActivityMonitor,
  Batteries as LinedCustomBatteries,
  CapsulePills as LinedCustomCapsulePills,
  CheckFile as LinedCustomCheckFile,
  Checklist as LinedCustomChecklist,
  ClearList as LinedCustomClearList,
  Clipboard as LinedCustomClipboard,
  ClockRewind as LinedCustomClockRewind,
  CodeReview as LinedCustomCodeReview,
  Container as LinedCustomContainer,
  ControlPolicy as LinedCustomControlPolicy,
  CornerUpRightSquare as LinedCustomCornerUpRightSquare,
  CryptoKey as LinedCustomCryptoKey,
  Disguise as LinedCustomDisguise,
  Domain as LinedCustomDomain,
  DomainRecord as LinedCustomDomainRecord,
  Filter as LinedCustomFilter,
  Fork as LinedCustomFork,
  Function as LinedCustomFunction,
  Heart as LinedCustomHeart,
  HeartCircle as LinedCustomHeartCircle,
  HeartList as LinedCustomHeartList,
  HeartFolder as LinedCustomHeartFolder,
  HeartMonitor as LinedCustomHeartMonitor,
  Heatmap as LinedCustomHeatmap,
  Helix as LinedCustomHelix,
  HelixAlt as LinedCustomHelixAlt,
  Hook as LinedCustomHook,
  Host as LinedCustomHost,
  HostAgent as LinedCustomHostAgent,
  Jira as LinedCustomJira,
  Key as LinedCustomKey,
  KeyLock as LinedCustomKeyLock,
  Library as LinedCustomLibrary,
  Lifeology as LinedCustomLifeology,
  LightBulb as LinedCustomLightBulb,
  LinkBroken as LinedCustomLinkBroken,
  MaxDate as LinedCustomMaxDate,
  MortarBoard as LinedCustomMortarBoard,
  NodeMesh as LinedCustomNodeMesh,
  NodeTree as LinedCustomNodeTree,
  OfficeBuilding as LinedCustomOfficeBuilding,
  Oncoprint as LinedCustomOncoprint,
  PasswordPolicy as LinedCustomPasswordPolicy,
  Planet as LinedCustomPlanet,
  PlotCurve as LinedCustomPlotCurve,
  PlotNeedle as LinedCustomPlotNeedle,
  PlotScatter as LinedCustomPlotScatter,
  Procedure as LinedCustomProcedure,
  Radar as LinedCustomRadar,
  Repository as LinedCustomRepository,
  ResetDate as LinedCustomResetDate,
  Root as LinedCustomRoot,
  Run as LinedCustomRun,
  Spaceship as LinedCustomSpaceship,
  StackedBar as LinedCustomStackedBar,
  Unavailable as LinedCustomUnavailable,
  UserKey as LinedCustomUserKey,
  UserShield as LinedCustomUserShield,
  UsersShield as LinedCustomUsersShield,
  Versions as LinedCustomVersions,
  Webhook as LinedCustomWebhook,
} from '../../../src/icons/linedCustom/';
import { Queued as FilledQueued } from '../../../src/icons/Queued';
import { Running as FilledRunning } from '../../../src/icons/Running';
import { SideBar as AdaptiveSidebar } from '../../../src/icons/SideBar';
import { XCircle as FilledXCircle } from '../../../src/icons/XCircle';
import { Container } from '../../storyComponents/Container';
import { Noop } from '../../storyComponents/Noop';
import { spacing } from '../../storyStyles';
import adaptiveMd from './adaptiveIcons.md';
import filledMd from './filledIcons.md';
import linedCustomMd from './linedCustomIcons.md';
import linedMd from './linedIcons.md';
import overviewMd from './overview.md';

const filledIcons = Object.entries({
  FilledCancel,
  FilledComplete,
  FilledError,
  FilledFile,
  FilledFolder,
  FilledHeart,
  FilledInfo,
  FilledQueued,
  FilledRunning,
  FilledXCircle,
});

const adaptiveIcons = Object.entries({
  AdaptiveChevronDown,
  AdaptiveGuide,
  AdaptiveSidebar,
});

const linedIcons = Object.entries({
  Activity,
  Airplay,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Anchor,
  Aperture,
  Archive,
  ArrowDownCircle,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowDown,
  ArrowLeftCircle,
  ArrowLeft,
  ArrowRightCircle,
  ArrowRight,
  ArrowUpCircle,
  ArrowUpLeft,
  ArrowUpRight,
  ArrowUp,
  AtSign,
  Award,
  BarChart,
  BatteryCharging,
  Battery,
  BellOff,
  Bell,
  Bluetooth,
  Bold,
  BookOpen,
  Book,
  Bookmark,
  Box,
  Briefcase,
  Calendar,
  CameraOff,
  Camera,
  Cast,
  CheckCircle,
  CheckSquare,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  Chrome,
  Circle,
  Clipboard,
  Clock,
  CloudDrizzle,
  CloudLightning,
  CloudOff,
  CloudRain,
  CloudSnow,
  Cloud,
  Code,
  Codepen,
  Coffee,
  Command,
  Compass,
  Copy,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftDown,
  CornerLeftUp,
  CornerRightDown,
  CornerRightUp,
  CornerUpLeft,
  CornerUpRight,
  Cpu,
  CreditCard,
  Crop,
  Crosshair,
  Database,
  Delete,
  Disc,
  DollarSign,
  DownloadCloud,
  Download,
  Droplet,
  Edit,
  ExternalLink,
  EyeOff,
  Eye,
  Facebook,
  FastForward,
  Feather,
  FileMinus,
  FilePlus,
  FileText,
  File,
  Film,
  Filter,
  Flag,
  FolderMinus,
  FolderPlus,
  Folder,
  Frown,
  Gift,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  GitHub,
  Gitlab,
  Globe,
  Grid,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  Image,
  Inbox,
  Info,
  Instagram,
  Italic,
  Key,
  Layers,
  Layout,
  LifeBuoy,
  Link2,
  Link,
  Linkedin,
  List,
  Loader,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Map,
  Maximize2,
  Maximize,
  Meh,
  Menu,
  MessageCircle,
  MessageSquare,
  MicOff,
  Mic,
  Minimize2,
  Minimize,
  MinusCircle,
  MinusSquare,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Move,
  Music,
  Navigation2,
  Navigation,
  Octagon,
  Package,
  Paperclip,
  PauseCircle,
  Pause,
  Percent,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  Phone,
  PieChart,
  PlayCircle,
  Play,
  PlusCircle,
  PlusSquare,
  Plus,
  Pocket,
  Power,
  Printer,
  Radio,
  RefreshCcw,
  RefreshCw,
  Repeat,
  Rewind,
  RotateCcw,
  RotateCw,
  Rss,
  Save,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Share,
  ShieldOff,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sidebar,
  SkipBack,
  SkipForward,
  Slack,
  Slash,
  Sliders,
  Smartphone,
  Smile,
  Speaker,
  Square,
  Star,
  StopCircle,
  Sun,
  Sunrise,
  Sunset,
  Tablet,
  Tag,
  Target,
  Terminal,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  ToggleLeft,
  ToggleRight,
  Trash,
  Trello,
  TrendingDown,
  TrendingUp,
  Triangle,
  Truck,
  Tv,
  Twitter,
  Type,
  Umbrella,
  Underline,
  Unlock,
  UploadCloud,
  Upload,
  UserCheck,
  UserMinus,
  UserPlus,
  UserX,
  User,
  Users,
  VideoOff,
  Video,
  Voicemail,
  Volume1,
  Volume2,
  VolumeX,
  Volume,
  Watch,
  WifiOff,
  Wifi,
  Wind,
  XCircle,
  XSquare,
  X,
  Youtube,
  ZapOff,
  Zap,
  ZoomIn,
  ZoomOut,
});

const linedCustomIcons = Object.entries({
  LinedCustomAccessPolicy,
  LinedCustomActivityFolder,
  LinedCustomActivityMonitor,
  LinedCustomBatteries,
  LinedCustomCapsulePills,
  LinedCustomCheckFile,
  LinedCustomChecklist,
  LinedCustomClearList,
  LinedCustomClipboard,
  LinedCustomClockRewind,
  LinedCustomCodeReview,
  LinedCustomContainer,
  LinedCustomControlPolicy,
  LinedCustomCornerUpRightSquare,
  LinedCustomCryptoKey,
  LinedCustomDisguise,
  LinedCustomDomain,
  LinedCustomDomainRecord,
  LinedCustomFilter,
  LinedCustomFork,
  LinedCustomHeart,
  LinedCustomHeartCircle,
  LinedCustomHeartList,
  LinedCustomHeartFolder,
  LinedCustomHeartMonitor,
  LinedCustomHeatmap,
  LinedCustomHelix,
  LinedCustomHelixAlt,
  LinedCustomHook,
  LinedCustomFunction,
  LinedCustomHost,
  LinedCustomHostAgent,
  LinedCustomJira,
  LinedCustomKey,
  LinedCustomKeyLock,
  LinedCustomLibrary,
  LinedCustomLifeology,
  LinedCustomLightBulb,
  LinedCustomLinkBroken,
  LinedCustomMaxDate,
  LinedCustomMortarBoard,
  LinedCustomNodeMesh,
  LinedCustomNodeTree,
  LinedCustomOfficeBuilding,
  LinedCustomOncoprint,
  LinedCustomPasswordPolicy,
  LinedCustomPlanet,
  LinedCustomPlotCurve,
  LinedCustomPlotNeedle,
  LinedCustomPlotScatter,
  LinedCustomProcedure,
  LinedCustomRepository,
  LinedCustomResetDate,
  LinedCustomRadar,
  LinedCustomRoot,
  LinedCustomRun,
  LinedCustomSpaceship,
  LinedCustomStackedBar,
  LinedCustomUnavailable,
  LinedCustomUserKey,
  LinedCustomUserShield,
  LinedCustomUsersShield,
  LinedCustomVersions,
  LinedCustomWebhook,
});

const IconBox: React.FC<any> = ({ name, icon: Icon }) => (
  <div
    style={{
      color: 'black',
      padding: `${spacing[4]} ${spacing[2]}`,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      background: 'white',
      borderRadius: spacing[2],
      boxShadow: '0px 2px 8px rgba(0, 0, 0, 0.13)',
      textAlign: 'center',
      wordBreak: 'break-word',
    }}
  >
    <Icon />
    <p style={{ fontWeight: 'bold', marginBottom: 0 }}>{name}</p>
  </div>
);

const FilledIconsStory: React.FC = () => (
  <Container
    containerStyles={{
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))',
      gap: `${spacing[4]} ${spacing[4]}`,
    }}
  >
    {filledIcons.map(([name, Icon], i) => (
      <IconBox key={i} icon={Icon} name={name.replace('Filled', '')} />
    ))}
  </Container>
);

const AdaptiveIconsStory: React.FC = () => (
  <Container
    containerStyles={{
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))',
      gap: `${spacing[4]} ${spacing[4]}`,
    }}
  >
    {adaptiveIcons.map(([name, Icon], i) => (
      <IconBox key={i} icon={Icon} name={name.replace('Adaptive', '')} />
    ))}
  </Container>
);

/** @deprecated */
const LinedIconsStory: React.FC = () => (
  <Container
    containerStyles={{
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
      gap: `${spacing[4]} ${spacing[4]}`,
    }}
  >
    {linedIcons.map(([name, Icon], i) => (
      <IconBox key={i} icon={Icon} name={name.replace('Lined', '')} />
    ))}
  </Container>
);

/** @deprecated */
const LinedCustomIconsStory: React.FC = () => (
  <Container
    containerStyles={{
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
      gap: `${spacing[4]} ${spacing[4]}`,
    }}
  >
    {linedCustomIcons.map(([name, Icon], i) => (
      <IconBox key={i} icon={Icon} name={name.replace('LinedCustom', '')} />
    ))}
  </Container>
);

storiesOf('Iconography', module)
  .add('Overview', () => <Noop />, {
    readme: { content: overviewMd },
  })
  .add('Lined Icons', () => <LinedIconsStory />, {
    readme: { content: linedMd },
  })
  .add('Lined Custom Icons', () => <LinedCustomIconsStory />, {
    readme: { content: linedCustomMd },
  })
  .add('Filled Icons', () => <FilledIconsStory />, {
    readme: { content: filledMd },
  })
  .add('Adaptive Icons', () => <AdaptiveIconsStory />, {
    readme: { content: adaptiveMd },
  });
